const express = require('express');
const events = require('events');
events.EventEmitter.defaultMaxListeners = 15;
const cookieParser = require('cookie-parser');
const owenerRouter = require('./routes/owenerRouter');
const userRouter = require('./routes/userRouter');
const productRouter = require('./routes/productRouter');
const landing_page = require('./routes/landing_page');
const logout= require('./routes/logout');
const login = require('./routes/loginpage');
const db = require('./config/mongoose_connection');
let path = require('path');
const app = express();
const port = 3000;
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.set('view engine', 'ejs');
app.use('/login', login);
app.use('/login/admin_login', login);
app.use('/owner', owenerRouter);
app.use('/admin/removeproduct', productRouter);
app.use('/logout', logout);
app.use('/products', productRouter);
app.use('/Home_page', userRouter);
app.use('/admin', owenerRouter);
app.use('/signin', landing_page);
app.use('/Home_page/cart', userRouter);
app.use('/Home_page/cart/remove', userRouter);
app.use('/Home_page/show_case', userRouter);
app.use('/Home_page/show_case/add_to_cart', userRouter);
app.use('/owner/admin_sigin', owenerRouter);
app.use('/owner/admin_sigin/admin_login', owenerRouter);
app.use('/owner/comadmin_login', owenerRouter);
app.use('logout/logout_all', logout);
app.use('/Home_page/shop', userRouter);
app.use('/admin/remove', owenerRouter);
app.use('/Home_page/profile', userRouter);
app.use('/Home_page/profile/add', userRouter);
app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});